import os
from datetime import datetime, timedelta
from sqlalchemy.pool import NullPool
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Common configuration for all environments: Dev, QA y Production
class Config:
    """
    Common configurations
    """
    # Secret key for the Flask application
    SECRET_KEY = os.environ.get("SECRET_KEY", None)

    # Secret key to sign JWT tokens
    JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY", None) 
    # Expiration settings and algorithm for JWT, in seconds
    JWT_ACCESS_TOKEN_EXPIRES = int(os.environ.get("JWT_EXPIRATION_DELTA", None))
    # Signature algorithm for JWT (e.g., HS256)
    JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", None)
    # TO ENABLE JWT WITH USE OF COOKIES
    JWT_TOKEN_LOCATION = os.environ.get("JWT_TOKEN_LOCATION", None)   # Search for the token in cookies

    # TO ENABLE JWT WITH USE OF COOKIES
    # JWT_ACCESS_COOKIE_NAME = os.environ.get("JWT_ACCESS_COOKIE_NAME", None)  # Cookie name
    # JWT_COOKIE_SECURE = os.environ.get("JWT_COOKIE_SECURE", False)          # True if you use HTTPS
    # JWT_COOKIE_CSRF_PROTECT = os.environ.get("JWT_COOKIE_CSRF_PROTECT", True)     # CSRF Protection
    # JWT_COOKIE_SAMESITE = os.environ.get("JWT_COOKIE_SAMESITE", None) # SameSite attribute for cookies (e.g., 'Lax', 'Strict', 'None')

    # TO ENABLE JWT WITH USE OF HEADERS
    JWT_HEADER_NAME = os.environ.get("JWT_HEADER_NAME", None) # Expected header name
    JWT_HEADER_TYPE = os.environ.get("JWT_HEADER_TYPE", None) # Prefix that the token must have in the header

    # Avoid using a connection pool, which is useful for environments without pooling support.
    SQLALCHEMY_ENGINE_OPTIONS = { "poolclass": NullPool }
    # It allows the Content-Disposition header to be accessible from the client, which is necessary for file downloads.
    CORS_EXPOSE_HEADERS = ["Content-Disposition"]


# Specific configurations for each environment:
class DevConfig(Config):
    """
    Development configurations
    """
    #FLASK
    # Enables debug mode for development, which provides detailed information about errors and automatically reloads the application when code changes are detected.
    FLASK_DEBUG = True

    #SQLALCHEMY
    # Database connection URI for the development environment, using an environment variable to obtain the database URL and specifying the schema to use.
    SQLALCHEMY_DATABASE_URI = os.environ.get("DB_DEV")

    # Enables tracking of changes to database objects, which can be useful for debugging but can impact performance, so it is generally disabled in production.
    SQLALCHEMY_TRACK_MODIFICATIONS = True

    #SQLALCHEMY_BINDS
    # Setting up an additional bind for SQLAlchemy, allowing you to connect to multiple databases within the same application.
    # In this case, a bind called 'db_name_bind' is defined with its own connection URI, also obtained from an environment variable and specifying the scheme to use.
    SQLALCHEMY_BINDS = {
        'db_name_bind': os.environ.get("DB_DEV_BIND"),
    }

    # Enables logging of SQL queries generated by SQLAlchemy, which can be useful for debugging and performance analysis, but is generally disabled in production to avoid logging overhead.
    SQLALCHEMY_ECHO = True

    # Environment configuration for Sentry, an error monitoring platform.
    # This allows categorizing errors reported by Sentry according to the environment in which they occur (in this case, "development" for the development environment).
    SENTRY_ENV = "development"


class QaConfig(Config):
    """
    QA Ambient configurations
    """
    FLASK_DEBUG = False
    SQLALCHEMY_DATABASE_URI = os.environ.get("DB_QA")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_BINDS = {
        'db_name_bind': os.environ.get("DB_QA_BIND"),
    }
    SENTRY_ENV = "release"


class ProdConfig(Config):
    """
    Production configurations
    """

    FLASK_DEBUG = False
    SQLALCHEMY_DATABASE_URI = os.environ.get("DB_PRD")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_BINDS = {
        'db_name_bind': os.environ.get("DB_PRD_BIND"),
    }
    SENTRY_ENV = "production"


# Mapping environment names to their respective configuration classes
app_config = {
    'dev': DevConfig,
    'qas': QaConfig,
    'prd': ProdConfig
}
